spring.application.name=clubes-futbol

spring.data.mongodb.uri=mongodb+srv://marliton445_db_user:marlon0810@cluster0.lpg77fw.mongodb.net/futbol_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=futbol_db

server.port=8207