spring.application.name=clubes-futbol

# MongoDB - cambia esto por tu URI de MongoDB Atlas o local
spring.data.mongodb.uri=mongodb://localhost:27017/futbol_db
spring.data.mongodb.database=futbol_db

# Para ver las queries en consola (util para desarrollo)
logging.level.org.springframework.data.mongodb.core=DEBUG
